language: c

script:
  - make && make test

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
          - lcov
      install:
        - gem install coveralls-lcov
      before_script:
        - mkdir build
        - cd build
        - cmake .. -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug
      after_success:
        - lcov --compat-libtool --directory . --capture --output-file coverage.info
        - coveralls-lcov coverage.info
    - os: linux
      compiler: gcc
      before_script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
    - os: linux
      compiler: clang
      before_script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
    - os: osx
      compiler: clang
      before_script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
