language: c

compiler: gcc

addons:
  apt:
    packages:
    - lcov

install:
  - gem install coveralls-lcov

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

script:
  - make && make test

after_success:
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info

