language: c
sudo: required

compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - mkdir build
  - cd build
  - cmake .. -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

script:
  - gcc --version
  - gcov --version
  - lcov --version
  - make && make test

after_success:
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info

