language: c

addons:
  apt:
    packages:
    - lcov

install:
  - gem install coveralls-lcov

before_script:
  - mkdir build
  - cd build
  - cmake .. $COVERAGE -DCMAKE_BUILD_TYPE=Debug

script:
  - make && make test

after_success:
  - if [[ "$COVERAGE" != "" ]]; then lcov --compat-libtool --directory . --capture --output-file coverage.info; fi
  - if [[ "$COVERAGE" != "" ]]; then coveralls-lcov coverage.info; fi


matrix:
  include:
    - os: linux
      compiler: gcc
      env: COVERAGE="-DCOVERAGE=1"
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang