version: '{build}'

image:
- Visual Studio 2015

  
clone_folder: 'c:\development\cutil'

environment:
  matrix:
    - cmake_generator: "Visual Studio 14 2015"
      cmake_arch: Win32
    - cmake_generator: "Visual Studio 14 2015"
      cmake_arch: x64
    
before_build:
  - 'mkdir c:\development\cutil\build'
  - 'cd c:\development\cutil\build'
  - 'cmake .. -G "%cmake_generator%" -A %cmake_arch%'
    
configuration:
  - Release
  
build:
  project: 'c:\development\cutil\build\cutil.sln'
  
test_script: 
  - 'cd C:\development\cutil\build'
  - 'ctest -C Release'